// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqvK-pp6gXoxd4ShY85wRrd-Z3Fogw0BA',
    appId: '1:58203854800:web:708c0548c33fc4c49d4bd5',
    messagingSenderId: '58203854800',
    projectId: 'foodapp-f5692',
    authDomain: 'foodapp-f5692.firebaseapp.com',
    databaseURL: 'https://foodapp-f5692-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-f5692.firebasestorage.app',
    measurementId: 'G-5NSE7056XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe2T6X_HrHmSJuvNfE9HU6sZ3qHtarD2Q',
    appId: '1:58203854800:android:c1fa30146e1dce279d4bd5',
    messagingSenderId: '58203854800',
    projectId: 'foodapp-f5692',
    databaseURL: 'https://foodapp-f5692-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-f5692.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBF8GnUH-P0lmsnw7rSzLNpLbNBlFLK2c',
    appId: '1:58203854800:ios:ca86d51971194ce09d4bd5',
    messagingSenderId: '58203854800',
    projectId: 'foodapp-f5692',
    databaseURL: 'https://foodapp-f5692-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-f5692.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBF8GnUH-P0lmsnw7rSzLNpLbNBlFLK2c',
    appId: '1:58203854800:ios:ca86d51971194ce09d4bd5',
    messagingSenderId: '58203854800',
    projectId: 'foodapp-f5692',
    databaseURL: 'https://foodapp-f5692-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-f5692.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqvK-pp6gXoxd4ShY85wRrd-Z3Fogw0BA',
    appId: '1:58203854800:web:cd5d88c7178dc2b39d4bd5',
    messagingSenderId: '58203854800',
    projectId: 'foodapp-f5692',
    authDomain: 'foodapp-f5692.firebaseapp.com',
    databaseURL: 'https://foodapp-f5692-default-rtdb.firebaseio.com',
    storageBucket: 'foodapp-f5692.firebasestorage.app',
    measurementId: 'G-7ECBGSQVYY',
  );

}